### ISSUE TITLE
Image is pasted as a URL link instead of image

### ISSUE THREAD

**Issue by mquan86** [cetinkaya/pastefromhtml#15]
**Steps:**
- Go to example web https://github.com/zim-desktop-wiki/zim-desktop-wiki
- Select and copy the image of Zim Desktop
- Paste as HTML to Zim

**Actual behaviour:**
- Image is pasted as an URL link (https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/develop/website/files/screenshots/zim-normal.png)

**Expected:**
- Image is pasted as image.

**Log:** (no error)
```
DEBUG: Action: pastefh
DEBUG: Action: reload_page
```

**Comment by cetinkaya** [comment]
Thanks the detailed report on this issue. 

This happens because the image in that website has a link to another page that is different from the source URL of the image. In other words, you can click on the image to go to another page. I am not 100% sure, but I think we cannot attach links to images in Zim. The contributor of image pasting code in pastefromhtml decided to keep the URL instead of the image in such a scenario. 

As a user of pastefromhtml, what is your opinion? Could you tell me what do you want to see when you paste?
  - Both the image and the link? (Image first, then link later? Link first, image later?)
  - Just the image?
  - Just the link?

**Comment by mquan86** [comment]
From end user point of view, I think most of people will expect that it pastes as just image. Normally end user cares that it displays as the same as original source they saw.
So paste as just the image from the `src` property of `img` tag would be ideal I think?

I test similar on MS OneNote and Word for example and it just pastes as image only.

**Comment by mquan86** [comment]
Of course, depend on how it is complex to implement such thing. 
If it is too hard and for example it is easier to implement paste as link first and then image later (as I see the HTML structure is a link wrap image), I think it is still ok and make sense.

**Comment by cetinkaya** [comment]
With the commit 5a20e6c,  I have added an option to choose whether to paste images instead of links. It can be selected via clicking the menu Edit/Preferences, then choosing Paste from HTML from Plugins tab and clicking the Configure button on the right side.


![option](https://user-images.githubusercontent.com/3178761/224882030-88401213-9225-4f43-9057-08c3a4267d0e.png)
